### ISSUE TITLE
Refactor the code so that it is "state" based

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#40]
[13:11] <+Brett824> it basically allows us to rearch to do what we've always wanted the tracker to do -- have the log read stuff to a state, and have the UI draw stuff from the state

This is step 1 in implementing network functionality, even though it has technically has nothing to do with networking.

Step 2 (transferring the state) can't be started until step 1 is complete, but should be relatively straightforward once step 1 is completed..

**Comment by Cracktuar** [comment]
So I did some work over the past two days and have managed to decouple the interface from the model.  This means we now have items and stuff behind the scene that can be passed around.  It's not great but I think it's a workable first draft.

**Comment by Zamiell** [comment]
Great work! On your fork though it appears you haven't pushed your changes.

**Comment by Cracktuar** [comment]
Ah I haven't yet!  I was just getting the final touches ready so that it'd actually show the current floor like the current version does.  I also need to clean up the code a bit but that can happen later today.  I'll let you know when I've pushed the changes

**Comment by Cracktuar** [comment]
Alright so I pushed the changes to item-splitting-dev on my fork - I haven't done anything with git for a while so I need to figure out how to get that merged up into my item-splitting branch and then finally the master branch, but you should be able to check it out/download it now.

I'll note that it's definitely not done yet - I decoupled it but there's still a few minor issues like the item description text being funky and less minor issues like random crashes.  I also haven't been able to test rerolled items yet because I'm bad at Isaac hah.

**Comment by Zamiell** [comment]
Just use Cheat Engine?

**Comment by Zamiell** [comment]
Close this issue now?

**Comment by Cracktuar** [comment]
I think you still have to separate the input stuff too actually, but maybe that should be a separate issue.

**Comment by Hyphen-ated** [comment]
yeah like, the code that parses the logs should have no pygame stuff in it, and we need that code to communicate with the display side by passing a single state object. we are closer to that than we were before, but we're not there yet.

thanks for doing all this work cracktuar!

**Comment by Cracktuar** [comment]
Ha no problem.  I was recovering from a procedure and had about 2 weeks of downtime at the time and I really like Binding of Isaac Races so I was like "eh what the heck sure"

**Comment by viroulep** [comment]
I'd like to bump this up.

Following the oral/chat discussion during Lost Child 2 I think it would definitely be nice to have the tracker to be able to write-to/read-from a distant server.

I don't think we are actually that far from being able to do that.
Some stuffs come to my mind :
- Define a tracker state in json (I think that's the easier format to parse/serialize from multiple languages)
- We need to move the parsing stuff to a separate class so that it would be easier to add a json frontend for the tracker (like a Parser abstract class + ParserTxt and ParserJson implementations)
- We need a small server side app where the racer could push to (with a kind of authentication token), and where the streamer could fetch from with the racer id.

**Comment by Zamiell** [comment]
Can close this now?

**Comment by Hyphen-ated** [comment]
yes, viroulep did the work
