### ISSUE TITLE
Make it work with Afterbirth

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#51]
1) The location of the log file changes.
2) The new alternate floors (Burning Basement, Flooded Caves, etc.) crash the tracker because it can't parse the floor.
3) ???

I know Sillypears did some work yesterday messing around with trying to make the tracker work, can you expand on this?

**Comment by sillypears** [comment]
I grabbed the latest code merged and added some of the changes/fixes to get this running, but I have the bug again where it doesn't show the last item picked up, but the one before it in the description area.

I'm not sure if I should do something about that, since I think @viroulep fixed that at some point.

**Comment by viroulep** [comment]
Could you push it to some branch of your repo so that I can have a look at it ?

**Comment by Zamiell** [comment]
Going to close this since it works now.
