### ISSUE TITLE
Tracker breaks upon going back from Afterbirth to Rebirth

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#61]
The tracker should be robust enough to automatically work on either version when the user switches back and forth between the vanilla game and the DLC.

**Comment by sillypears** [comment]
I think the problem here is that if you have a log.txt in both 'The Binding of Isaac Afterbirth' and 'The Binding of Isaac Rebirth' how does it know which version you are actually running? The exe is the same. 

The only thing I can think of doing would be to check for the presence of the 'afterbirth.a' file in the game directory? If afterbirth.a exists then I guess the DLC is downloaded and actively being used, so use the Afterbirth log.txt, otherwise use the Rebirth log.txt

Does that sound like a solution @Zamiell?

**Comment by Zamiell** [comment]
Yes, that sounds perfect.

**Comment by sillypears** [comment]
I'm assuming the statement to be true, can you just uninstall/reinstall the dlc a few times to verify that the afterbirth.a gets removed/add? I will attempt to write this in and make a PR on it, but I think there are people more capable at implementing this than me :) :+1:

**Comment by DrSilence** [comment]
What a hassle to find the game directory for each platform ...
In my opinion it would be easier to check which is the "newer" log file.
Obviously works only if the game is running once before starting the item_tracker.

Any opinions !?

**Comment by Inschato** [comment]
I incidentally wrote some steam related code (for a different project) that might be helpful depending how you approach this. It's not completely finished..

http://pastebin.com/wdUWzx1s

**Comment by sillypears** [comment]
Glad you posted it since I was going to just steal it @Inschato.

@DrSilence I feel that isn't a very reliable method, as if the game crashes, I believe the log.txt is removed or copied as a crash log (something like that). It's better to check that the Afterbirth DLC is actually installed, as there is no way to play Rebirth if the afterbirth.a file exists as far as I know.

**Comment by Zamiell** [comment]
"can you just uninstall/reinstall the dlc a few times to verify that the afterbirth.a gets removed/add?"

I've just done this and afterbirth.a is removed/added as expected. Go ahead with the PR.

**Comment by sillypears** [comment]
I'll work on it in ~6 hours unless someone beats me to it. Thanks for verifying Zam :100:

**Comment by Zamiell** [comment]
I guess the consensus is that adding Inschato's check is too much code.

**Comment by sillypears** [comment]
I think the consensus was to use the last working Rebirth version, as items have changed how they work in Afterbirth. Wouldn't make sense to have the Afterbirth descriptions for Rebirth versions of the items.
