### ISSUE TITLE
[New Feature] New line, objects in the room

### ISSUE THREAD

**Issue by Fran-Rg** [Hyphen-ated/RebirthItemTracker#69]
I saw this tracker: http://kst.io/binding_of_isaac_identifier
It is possible to see the objects description in the room before picking them. I don't know if it's possible with the log.txt to do that.
The list of item would be displayed in another line of object (empty at the beginning of each room) and it could be decided from the options to show it or not.

**Comment by sillypears** [comment]
I don't see the purpose of this feature, as it's an item tracker, not an item identifier.  This also appears to be using some memory scraping, which is not possible from the log.txt. The log only get written to when you pick up an item. 

Not to mention how the project you linked would only be used by people who are casually playing the game and probably don't know what each item does.

**Comment by Fran-Rg** [comment]
I kinda use the item tracker in this purpose. Once I picked I generally check what it does in detail

**Comment by sillypears** [comment]
I'd suggest using PlatGod for that purpose only because that is where all new discoveries usually wind up first. You'd have to wait until someone builds out a new release of the item tracker in order for you to see everything. Plus I believe if you click on a picked up item, it takes you directly to platgod anyway.
